### ISSUE TITLE
MathQuill not compatible with answers that have units

### ISSUE THREAD

**Issue by gajennings** [openwebwork/mathquill#7]
See Paul Pearson's bug report
https://bugs.webwork.maa.org/show_bug.cgi?id=4705

**Comment by pstaabp** [comment]
I think this is related to openwebwork/webwork2#1804 and there is a possible fix at #6.

**Comment by gajennings** [comment]
If the student clicks the MathQuill textbox button (Tt) before entering answers with units then everything works.  I didn't see that at first, students may not see it either, so I added a note to the problem instructing MathQuill users to click Tt.  Maybe the right solution is to leave MathQuill alone and tell instructors to recommend the textbox when things don't work.

**Comment by paultpearson** [comment]
Is there a way that a PG file can either disable MathQuill or automatically select the Tt option of MathQuill so that students and professors don't have to do anything special to make the answer checker work?  Asking professors and students to implement a work around seems like a less than ideal solution to this problem.

**Comment by drgrice1** [comment]
This was fixed by a change to PG's parsing when MathQuill is enabled.
